# Generated by Django 2.2.19 on 2022-03-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(max_length=50, unique=True)),
                ('password', models.TextField(max_length=50, unique=True)),
                ('invite_code', models.TextField(default='9n6G6y')),
                ('activation', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
